# Generated by Django 5.2.5 on 2025-09-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobseeker_resume_vacancy_application_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('training', 'Training & Education'), ('counseling', 'Career Counseling'), ('financial', 'Financial Assistance'), ('housing', 'Housing Support'), ('legal', 'Legal Services'), ('health', 'Healthcare'), ('childcare', 'Childcare'), ('other', 'Other Services')], max_length=20)),
                ('description', models.TextField()),
                ('contact_info', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('author', models.CharField(default='Career Advisor', max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='advisory/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.advisorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.referralpartner')),
            ],
        ),
    ]
