# Generated by Django 5.2.5 on 2025-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_advisorycategory_referralpartner_advisoryarticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
