# Generated by Django 5.2.5 on 2025-09-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_vacancy_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('ZAR', 'South African Rand (R)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='ZAR', max_length=3),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
