# Generated by Django 5.2.5 on 2025-10-09 15:40

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_vacancy_currency_vacancy_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='vacancies/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif']), jobs.models.validate_file_size]),
        ),
    ]
