# Generated by Django 5.2.5 on 2025-10-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_vacancy_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_upload_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
